/* Optional local smoke test: it exits successfully unless explicitly configured. */
import { getConfig } from '../config.js';
import { TalosMcpClient } from '../mcp/TalosMcpClient.js';
const required=['TALOS_MCP_COMMAND','TALOS_MCP_ARGS','TALOS_API_URL'];
if(!required.every(key=>process.env[key])){console.log('Skipping local integration test: TALOS_MCP_COMMAND, TALOS_MCP_ARGS, and TALOS_API_URL are required.');process.exit(0)}
const config=getConfig();const mcp=new TalosMcpClient(config);
const terminal=new Set(['passed','failed','stopped','completed','cancelled']);
const delay=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
try{await mcp.connect();const projects=await mcp.listProjects();if(!projects.length)throw new Error('No Talos projects available for local integration test.');const project=projects.find(value=>!value.environments.some(env=>/prod(uction)?/i.test(`${env.name} ${env.baseUrl??''}`)))??projects[0];const environment=project.environments.find(value=>!/prod(uction)?/i.test(`${value.name} ${value.baseUrl??''}`));if(!environment)throw new Error('No non-production Talos environment available.');const run=await mcp.runTest({projectId:project.id,environmentId:environment.id,intent:'Verify the configured local non-production project is reachable.',wait:false});const response=await fetch(`${config.TALOS_API_URL}/api/runs/${run.runId}/stream`,{headers:config.TALOS_API_KEY?{Authorization:`Bearer ${config.TALOS_API_KEY}`}:{}});if(!response.ok)throw new Error(`SSE endpoint returned ${response.status}`);await response.body?.cancel();const deadline=Date.now()+10*60_000;let final=await mcp.getRun(run.runId,true);while(!terminal.has(final.status.toLowerCase())&&Date.now()<deadline){await delay(3_000);final=await mcp.getRun(run.runId,true)}if(!terminal.has(final.status.toLowerCase()))throw new Error(`Run ${run.runId} did not reach a terminal state within 10 minutes.`);console.log(`Local integration smoke test passed for run ${run.runId} (${final.status}).`)}finally{await mcp.close()}
