import type { App } from '@slack/bolt';
import { z } from 'zod';
import type { TalosMcpClient } from '../mcp/TalosMcpClient.js';
import type { RunThreadStore } from '../state/RunThreadStore.js';
import { RunStreamClient } from '../talos/runStreamClient.js';
import { StartAndMonitorRun } from '../talos/startAndMonitorRun.js';
import { bugBlocks } from './blocks/bugBlocks.js';
import { logger } from '../logger.js';
const Payload=z.object({value:z.string().uuid()});
export function registerActions(app:App,deps:{mcp:TalosMcpClient;store:RunThreadStore;stream:RunStreamClient}){const lifecycle=new StartAndMonitorRun(deps);const location=(body:any)=>({channel:body.channel.id,thread_ts:body.message.thread_ts??body.message.ts});
 app.action('talos_open_run',async({ack}:any)=>{await ack()});
 app.action('talos_stop_run',async({ack,body,client,action}:any)=>{await ack();const {value:runId}=Payload.parse(action);try{await deps.mcp.stopRun(runId);await client.chat.postMessage({...location(body),text:`Stop requested for Talos run ${runId}.`})}catch(error){logger.warn('Stop action failed',{runId,error});await client.chat.postMessage({...location(body),text:'Talos could not stop the run. Please check Talos and try again.'})}});
 app.action('talos_rerun',async({ack,body,client,action}:any)=>{await ack();const {value:oldRunId}=Payload.parse(action);if(!await deps.store.dedupe(`rerun:${oldRunId}:${body.user.id}`,600))return;const old=await deps.store.get(oldRunId);if(!old){await client.chat.postMessage({...location(body),text:'I could not find the previous run parameters.'});return}try{await lifecycle.start({...old,projectName:old.projectId,environmentName:old.environmentId,label:'Talos rerun'},client)}catch(error){logger.warn('Rerun failed',{runId:oldRunId,error});await client.chat.postMessage({...location(body),text:'Talos could not start the rerun. Check agent logs.'})}});
 app.action('talos_confirm_run',async({ack,body,client,action}:any)=>{await ack();const {value:id}=Payload.parse(action),pending=await deps.store.getPending(id);if(!pending||pending.userId!==body.user.id){await client.chat.postMessage({...location(body),text:'This confirmation is expired or belongs to another user.'});return}if(!await deps.store.dedupe(`confirm:${id}`,600))return;const request=await deps.store.takePending(id);if(!request)return;try{await lifecycle.start({...request,label:'Confirmed Talos test'},client)}catch(error){logger.warn('Confirmed run failed',{error});await client.chat.postMessage({...location(body),text:'Talos could not start the confirmed run. Check agent logs.'})}});
 app.action('talos_cancel_run',async({ack,body,client,action}:any)=>{await ack();const {value:id}=Payload.parse(action),pending=await deps.store.getPending(id);if(!pending||pending.userId!==body.user.id){await client.chat.postMessage({...location(body),text:'This confirmation is expired or belongs to another user.'});return}if(!await deps.store.dedupe(`cancel:${id}`,600))return;await deps.store.takePending(id);await client.chat.postMessage({...location(body),text:'Cancelled the pending Talos run.'})});
 app.action('talos_show_bugs',async({ack,body,client,action}:any)=>{await ack();const {value:runId}=Payload.parse(action);try{const run=await deps.mcp.getRun(runId,true);await client.chat.postMessage({...location(body),text:`Bugs for Talos run ${runId}`,blocks:bugBlocks(run.bugs??[],run.webUrl)})}catch(error){logger.warn('Bug lookup failed',{runId,error});await client.chat.postMessage({...location(body),text:'Talos could not retrieve bugs for this run.'})}});
}
