import type { App } from '@slack/bolt';
import type { TalosMcpClient } from '../mcp/TalosMcpClient.js';
import type { RunThreadStore } from '../state/RunThreadStore.js';
import { resolveRunRequest } from '../talos/resolveRunRequest.js';
import { RunStreamClient } from '../talos/runStreamClient.js';
import { runStartedBlocks } from './blocks/runStartedBlocks.js';
import { runProgressBlocks } from './blocks/runProgressBlocks.js';
import { runResultBlocks, runResultText } from './blocks/runResultBlocks.js';
import { errorBlocks } from './blocks/errorBlocks.js';
import { logger } from '../logger.js';
export function registerEvents(app:App,deps:{mcp:TalosMcpClient;store:RunThreadStore;stream:RunStreamClient}){async function handle({event,client,body}:any){const eventId=body?.event_id??`${event.channel}:${event.ts}`; if(!await deps.store.dedupe(eventId))return; const channel=event.channel; const threadTs=event.thread_ts??event.ts; await client.chat.postMessage({channel,thread_ts:threadTs,text:'Talos is resolving your request…'}); const text=event.text??''; if(/\bstop\b/i.test(text)){const active=await deps.store.latest(channel,threadTs); if(active){await deps.mcp.stopRun(active.runId); await client.chat.postMessage({channel,thread_ts:threadTs,text:`Stop requested for Talos run ${active.runId}.`});} return}
 try{const projects=await deps.mcp.listProjects(); const testsByProject=new Map(); for(const p of projects)testsByProject.set(p.id,await deps.mcp.listTests(p.id).catch(()=>[])); const r=resolveRunRequest({text,projects,testsByProject}); if(r.kind!=='resolved'){await client.chat.postMessage({channel,thread_ts:threadTs,text:r.message,blocks:errorBlocks(r.message)}); return} if(r.requiresConfirmation){await client.chat.postMessage({channel,thread_ts:threadTs,text:`Production-like environment requires confirmation before running: ${r.environment.name}`}); return} const run=await deps.mcp.runTest({projectId:r.project.id,environmentId:r.environment.id,intent:r.intent,testId:r.test?.id,wait:false}); await deps.store.save({runId:run.runId,teamId:body?.team_id,channelId:channel,threadTs,userId:event.user,projectId:r.project.id,environmentId:r.environment.id,intent:r.intent,testId:r.test?.id,webUrl:run.webUrl,startedAt:new Date().toISOString()}); await client.chat.postMessage({channel,thread_ts:threadTs,text:`Talos test started: ${run.webUrl??run.runId}`,blocks:runStartedBlocks({project:r.project.name,environment:r.environment.name,intent:r.intent,status:run.status,runId:run.runId,webUrl:run.webUrl})}); let progressTs:string|undefined,lastSent=0,bugs=0; void deps.stream.stream(run.runId,async e=>{try{if(e.type==='progress'&&Date.now()-lastSent>2500){lastSent=Date.now(); const msg={channel,thread_ts:threadTs,text:'Talos run progress',blocks:runProgressBlocks({title:`Talos is testing ${r.project.name} — ${r.environment.name}`,currentStep:e.currentStep,browserSteps:e.browserSteps,bugsObserved:bugs,plan:e.plan})}; if(progressTs) await client.chat.update({...msg,ts:progressTs}); else {const m=await client.chat.postMessage(msg); progressTs=m.ts as string;}} if(e.type==='bug')bugs++; if(e.type==='done'){const full=await deps.mcp.getRun(run.runId,true).catch(()=>({runId:run.runId,status:e.status??'failed',summary:'Run completed; final MCP retrieval failed.',webUrl:run.webUrl})); await deps.store.markCompleted(run.runId); await client.chat.postMessage({channel,thread_ts:threadTs,text:runResultText(full as any),blocks:runResultBlocks(full as any)});}}catch(err){logger.warn('Slack progress update failed',{runId:run.runId,error:err})}}); }catch(err){logger.error('Request failed',{error:err}); await client.chat.postMessage({channel,thread_ts:threadTs,text:'Talos could not start the run. Check agent logs.',blocks:errorBlocks('Talos could not start the run. Check agent logs.')});}}
 app.event('app_mention',handle); app.event('message',async(args:any)=>{if(args.event.channel_type==='im')await handle(args)}); app.event('app_home_opened',async({event,client}:any)=>{await client.chat.postMessage({channel:event.channel??event.user,text:'Try: Test staging checkout'}).catch(()=>undefined)}); app.event('agent_view' as any, async()=>{}); app.event('app_context_changed' as any, async()=>{})}
